# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uJePiJTaGzs5fghj3CWeGgWwzsuSQ_JB
"""

pip install pyotp qrcode[pil]

!pip install pyotp qrcode[pil]

import pyotp
import qrcode

# 1. Sinh secret key
secret = pyotp.random_base32()
print("SECRET:", secret)

# 2. Ghi secret ra file để dùng lại
with open("secret.txt", "w") as f:
  f.write(secret)

# 3. Tạo URI chuẩn otpauth
totp = pyotp.TOTP(secret)
uri = totp.provisioning_uri(name="user@example.com", issuer_name="MyMFAApp")
print("URI:", uri)

# 4. Tạo mã QR từ URI
img = qrcode.make(uri)

# 5. Lưu mã QR thành file ảnh (ví dụ: PNG)
img.save("qrcode.png")

print("QR code saved as qrcode.png")

# 4. Tạo mã QR từ URI
img = qrcode.make(uri)

# 5. Lưu mã QR thành file ảnh (ví dụ: PNG)
img.save("qrcode.png")

print("QR code saved as qrcode.png")

# prompt: mở ảnh mã qr code

from IPython.display import Image, display
display(Image('qrcode.png'))

import pyotp

# 1. Đọc lại secret key từ file
with open("secret.txt", "r") as f:
    secret = f.read().strip()

totp = pyotp.TOTP(secret)

# 2. Bước 1: Nhập mật khẩu
password = input("Nhập mật khẩu: ")
if password != "123456":
    print("❌ Mật khẩu sai!")
else:
    # 3. Bước 2: Nhập mã OTP
    otp = input("Nhập mã OTP từ Google Authenticator: ")
    if totp.verify(otp):
        print("✅ Xác thực thành công! Bạn đã đăng nhập.")
    else:
        print("❌ Mã OTP sai hoặc hết hạn.")